version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rust-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data   # backend เก็บไฟล์ index/metadata ลง host
    environment:
      - RUST_LOG=info

  frontend:
    build: ./frontend
    container_name: leptos-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - BACKEND_URL=http://backend:8000